name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
    - uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ubuntu-latest-node-12.x-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
            ubuntu-latest-node-12.x-yarn-
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
         node-version: 12.x
    - name: install
      run: yarn
    - name: build
      run: yarn build

    - uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build Docker Image and Deploy to k8s
      run: |
        gcloud auth configure-docker --quiet
        docker build . -f Dockerfile -t "nasr/scheduler:$(git rev-parse --short HEAD)"
        docker tag "nasr/scheduler:$(git rev-parse --short HEAD)" gcr.io/nasr-learn/nasr/scheduler:latest
        docker push gcr.io/nasr-learn/nasr/scheduler

